# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'WalkMyDog' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WalkMyDog
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Analytics'

  pod 'GoogleSignIn'
  pod 'FBSDKLoginKit'
  pod 'Alamofire'
  pod 'FSCalendar'
  pod 'PanModal'
  pod 'Kingfisher', '~> 6.0'
  pod 'JVFloatLabeledTextField'

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxCoreLocation'
  pod 'RxViewController'

  target 'WalkMyDogTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WalkMyDogUITests' do
    # Pods for testing
  end
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
  end

end
