# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WalkMyDog' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WalkMyDog
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Analytics'
  pod 'Alamofire'

  target 'WalkMyDogTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WalkMyDogUITests' do
    # Pods for testing
  end

end
